import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import PathnameComponent from "@/components/pathname";
import Navbar from "@/components/ui/navbar";
import React from "react";



const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Red Bridge Construction",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {

    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <Navbar/>
            {children}
            </body>
        </html>
    );
}